### PR TITLE
(#83) [Fixed]: Mypy fixes in admin, models and manager accounts files.

### PR DESCRIPTION
**Pull request by francescarpi**
mypy fixes.

https://github.com/GeeksCAT/anem-per-feina/issues/83

Files affected:

accounts/admin.py
accounts/models.py
accounts/managers.py

### CODE REVIEW

**Comment by jbagot** [comment]
Have you take a decision about mypy? Do you want to keep it? Because mypy in the pipeline is deactivated because there are 200+ errors related with it. If you want to keep it, fine for me, but you should fix all the errors and then activate the pipeline check.
Or on the other hand, skip it, and don't put efforts solving this mypy errors.
From my point of view, my opinion is that we can skip and remove mypy. If someone wants to write code with typing it's fine, but change all the code to be mypy compliant is a waste of time in this project, we only have 2 weeks more and I don't know if it's worth it. But up to the backend team.

**Comment by francescarpi** [comment]
> Have you take a decision about mypy? Do you want to keep it? Because mypy in the pipeline is deactivated because there are 200+ errors related with it. If you want to keep it, fine for me, but you should fix all the errors and then activate the pipeline check.
> Or on the other hand, skip it, and don't put efforts solving this mypy errors.
> From my point of view, my opinion is that we can skip and remove mypy. If someone wants to write code with typing it's fine, but change all the code to be mypy compliant is a waste of time in this project, we only have 2 weeks more and I don't know if it's worth it. But up to the backend team.

See this issue @jbagot 

https://github.com/GeeksCAT/anem-per-feina/issues/83

We know it's disabled at the moment.  We are fixin all files in diferents pull request. When all be done, we will enable `mypy` again.

**Comment by XaviTorello** [comment]
I agree with @jbagot that this should not be a core requirement during this Hacktoberfest, but if someone will submit a PR to learn more about type annotations I'm fine with this :)

**Review by XaviTorello — APPROVED** [review]
Great, many thanks @francescarpi 💪

**Comment by francescarpi** [comment]
Ok, thanks for your comments!

**Pull request merged**
