### PR TITLE
Add django-environ to manage environment variables.

### PR DESCRIPTION
**Pull request by fullonic**
This PR improves #43 by using `django-environ` to deal with environment variables.

### CODE REVIEW

**Comment by francescarpi** [comment]
@fullonic I'm not sure is necessary load `.env` file

```python
# reading .env file
environ.Env.read_env()
```

https://github.com/joke2k/django-environ

Can you confirm me if it's not necessary?

Thanks!

**Comment by fullonic** [comment]
As far as I understood, that is necessary if we have .env file, which we don't have yet. That would be necessary once we have the app running on docker containers and a docker-compose file. Should I add now or wait for that moment?

**Comment by francescarpi** [comment]
@jbagot what do you think about `.env` file? Do I approve the PR now and implement the `read_env` at the future?

**Review by XaviTorello — CHANGES_REQUESTED** [review]
Looks good to me, many thanks @fullonic 🍺 

Will be great if we define the initial setup for reading from an .env file as @francescarpi suggests 👍

**Comment by fullonic** [comment]
I already made the changes. 
@XaviTorello @francescarpi

**Review by XaviTorello — APPROVED** [review]
LGTM! Ty @fullonic 🍻

**Comment by XaviTorello** [comment]
@francescarpi to simplify conflict resolution do not merge it before #48 please

**Comment by francescarpi** [comment]
Not merge until #48 will be done.

**Review by jbagot — APPROVED** [review]
For me it's fine, but would be nice to add a `.env.sample` file with some example environ vars. And then you have to copy the `.env.sample` file to `.env` file in your local but you NEVER have to push `.env` in the repository.
With the `.env` you will be able to change the env vars in your local, we will use the .env file when we'll create the docker-compose.

**Comment by fullonic** [comment]
@francescarpi PR #48 was approved and  I already solved the conflicts with this PR.

**Comment by francescarpi** [comment]
I'll merge it later. Good job!

**Comment by francescarpi** [comment]
Hi @fullonic , 

Could you make a rebase against master, pls?

**Pull request merged**
