### PR TITLE
Add more job categories

### LINKED ISSUE #167: Improve job categories
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add more job categories

### PR DESCRIPTION
**Pull request by jbagot**
## Description
Fix #167 

Added more categories

## Code formating

The code has to be well formatted following the formatting rules. For example in Python the code has to follow the PEP8.

Before create your PR, please make sure your code is well formatted and styled doing:
```bash
$ >> pre-commit run --all
```

### CODE REVIEW

**Comment by jbagot** [comment]
I didn't do the makemessages because we have the hook right @XaviTorello ?

**Review by XaviTorello — CHANGES_REQUESTED** [review]
Not sure if it's a good idea if we combine the category with the experience.

Maybe it's better to define another field for the experience (not necessary right now) and keep the category as simple as possible.

What do you think @jbagot @GeeksCAT/backend?

**Comment by jbagot** [comment]
I removed it

**Review by XaviTorello — APPROVED** [review]
Great many thanks!! 🍻

**Pull request merged**
