### PR TITLE
Add SonarCloud to GitHub Actions

### PR DESCRIPTION
**Pull request by mcmontseny**
Add SonarCloud analysis inside GitHub Actions.

### CODE REVIEW

**Review by XaviTorello — CHANGES_REQUESTED** [review]
Great! I love it @mcmontseny :)

Maybe it's better if we keep it in another job (or in another action) to isolate SonarCloud tests and do not broke agreed testing worklow

In some cases maybe it's a good idea to start just identifying SC issues and do not enforce to accomplish it for each PR.

What do you think @francescarpi?

**Comment by mcmontseny** [comment]
> ¡Excelente! Me encanta @mcmontseny :)
> 
> Tal vez sea mejor si lo mantenemos en otro trabajo (o en otra acción) para aislar las pruebas de SonarCloud y no romper el trabajo de prueba acordado.
> 
> En algunos casos, tal vez sea una buena idea comenzar a identificar problemas de SC y no hacer cumplir para lograrlo para cada RP.
> 
> ¿Qué opinas @francescarpi ?

**Comment by mcmontseny** [comment]
> Great! I love it @mcmontseny :)
> 
> Maybe it's better if we keep it in another job (or in another action) to isolate SonarCloud tests and do not broke agreed testing worklow
> 
> In some cases maybe it's a good idea to start just identifying SC issues and do not enforce to accomplish it for each PR.
> 
> What do you think @francescarpi?

Hi @XaviTorello, thanks for your review.

I believe is better to create a new Gitflow.

**Comment by francescarpi** [comment]
Hi! Same here. I also prefer a new flow.
Good job!

**Comment by mcmontseny** [comment]
> Hi! Same here. I also prefer a new flow.
> Good job!

Hi @francescarpi, new workflow is integrated. Do you need anything or task is done? Thanks

**Review by francescarpi — APPROVED** [review]

**Comment by francescarpi** [comment]
For me that's all. I don't know if for @XaviTorello it's already ok.

**Review by XaviTorello — APPROVED** [review]
Great!! Ty @mcmontseny 🍻

**Pull request merged**
